name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # 'windows-latest', 'macos-latest'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv .venv
        ./.venv/bin/pip install --upgrade pip
        ./.venv/bin/pip install -r requirements.txt

    - name: Run tests
      run: |
        ./.venv/bin/pytest

    # - name: Upload test results (optional)
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: test-results
    #     path: ./tests/test_results.xml
